// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	messages: {
		/**
		 * Decentralchain + Svelte
		 */
		title: string
		/**
		 * Demo project for Decentralchain Signer authentication
		 */
		description: string
	}
	login: {
		/**
		 * Log in
		 */
		login: string
		/**
		 * Logging in...
		 */
		logging: string
		/**
		 * Logged  in as {address}
		 * @param {string} address
		 */
		logged: RequiredParams<'address'>
	}
	footer: {
		/**
		 * Powered by
		 */
		poweredby: string
		/**
		 * Decentralchain
		 */
		decentralchain: string
	}
}

export type TranslationFunctions = {
	messages: {
		/**
		 * Decentralchain + Svelte
		 */
		title: () => LocalizedString
		/**
		 * Demo project for Decentralchain Signer authentication
		 */
		description: () => LocalizedString
	}
	login: {
		/**
		 * Log in
		 */
		login: () => LocalizedString
		/**
		 * Logging in...
		 */
		logging: () => LocalizedString
		/**
		 * Logged  in as {address}
		 */
		logged: (arg: { address: string }) => LocalizedString
	}
	footer: {
		/**
		 * Powered by
		 */
		poweredby: () => LocalizedString
		/**
		 * Decentralchain
		 */
		decentralchain: () => LocalizedString
	}
}

export type Formatters = {}
